apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: predictable-metrics
  name: predictable-metrics
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: predictable-metrics
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: predictable-metrics
    spec:
      containers:
      - image: gcr.io/cloud-platform-207208/dynatrace-predictable-metrics
        imagePullPolicy: Always
        name: predictable-metrics
        ports:
        - containerPort: 2112
        resources:
          requests:
            cpu: 10m
            memory: 64M
          limits:
            cpu: 50m
            memory: 128M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "2112"
    prometheus.io/scrape: "true"
  labels:
    run: predictable-metrics
  name: predictable-metrics
spec:
  ports:
  - port: 2112
    protocol: TCP
    targetPort: 2112
  selector:
    run: predictable-metrics
  sessionAffinity: None
  type: ClusterIP
